// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TscLoanManagement.TSCDB.Infrastructure.Data.Context;

#nullable disable

namespace TscLoanManagement.Migrations
{
    [DbContext(typeof(TSCDbContext))]
    [Migration("20260220113843_Baseline_20260220")]
    partial class Baseline_20260220
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TscLoanManagement.TSCDB.Application.DTOs.DealerDashboardSummaryDto", b =>
                {
                    b.Property<decimal?>("AccruedDelayedInterestActive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AccruedInterestActive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ActiveLoansCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("AvailableLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CLosedLoansCount")
                        .HasColumnType("int");

                    b.Property<int?>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("DealershipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DelayedInterestEarnedActive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DisbursementPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestEarnedActive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LoansSanctionedPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrincipalOutstandingActive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProcessingFeeEarnedActive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProcessingFeesReceivedActive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmountPending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDelayedInterestEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalInterestEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalOutstandingActive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalPrincipalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalProcessingFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalSanctionLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalWaiversAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UtilizationPercent")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.Permission", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.Role", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.RolePermission", b =>
                {
                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRepresentative")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.DDR.DDR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DDRNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfWithdraw")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DelayedROI")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GSTOnProcessingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HoldBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("HoldDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("InterestWaiver")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ProcessingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProcessingFeeReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RejectionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SelectedProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SettledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("SuggestedProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UtrNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("DDRs");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.DDR.DDRDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DdrId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DDRDocuments");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.BorrowerDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadharNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AddressAgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AddressAgreementExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddressStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerCPinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerCState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerPPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerPState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CIBILScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipWithEntity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("BorrowerDetails");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.ChequeDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateHandover")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsENach")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MandateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("MandateEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MandateStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MandateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxDebitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("ChequeDetails");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AgreementExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlternativeContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternativeEmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIBILOfEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfFacilityAgreement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfIncorporation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealershipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealershipPAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DelayROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DocumentationCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GSTOnDocCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GSTOnProcessingCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GSTRegStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoanProposalNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSMERegistrationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSMEStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSMEType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ParkingAgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ParkingAgreementExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParkingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkingYardAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkingYardCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkingYardPinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkingYardState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProcessingCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ROIPerLakh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelationshipManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ShopAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopPinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalSanctionLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.DocumentUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BorrowerDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuarantorDetailsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerDetailsId");

                    b.HasIndex("DealerId");

                    b.HasIndex("GuarantorDetailsId");

                    b.ToTable("DocumentUpload");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.GuarantorDetails", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("AadharNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AddressAgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AddressAgreementExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddressStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CIBILScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorCPinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorCState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorPPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorPState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipWithBorrower")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("GuarantorDetails");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.SecurityDepositDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AgreementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIBILOfEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRefunded")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DelayROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DocumentationCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GSTOnDocCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GSTOnProcessingCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ProcessingCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ROIPerLakh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalSanctionLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UTRNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("SecurityDepositDetails", t =>
                        {
                            t.HasTrigger("trg_UpdateDealersFromSecurityDeposit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.BuyerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DDRId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.ToTable("BuyerInfos");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DDRId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfWithdraw")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DelayedROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GSTOnProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestWaiver")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LoanDetailId")
                        .HasColumnType("int");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProcessingFeeReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SelectedProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SettledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SuggestedProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UtrNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DDRId");

                    b.HasIndex("DealerId");

                    b.HasIndex("LoanDetailId")
                        .IsUnique()
                        .HasFilter("[LoanDetailId] IS NOT NULL");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.LoanAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanAttachments");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.LoanDocumentUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanDocumentUploads");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.LoanPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DelayedInterestEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaymentReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalReceived")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanPayments");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.VehicleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DDRId")
                        .HasColumnType("int");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DDRId")
                        .IsUnique()
                        .HasFilter("[DDRId] IS NOT NULL");

                    b.HasIndex("LoanId")
                        .IsUnique()
                        .HasFilter("[LoanId] IS NOT NULL");

                    b.ToTable("VehicleInfos");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanDocuments.LoanDocumentActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryNoteNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanDocumentMasterId")
                        .HasColumnType("int");

                    b.Property<string>("ToPerson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoanDocumentMasterId");

                    b.ToTable("LoanDocumentActivities");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanDocuments.LoanDocumentMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfDisbursement")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakeModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcuredFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tenure")
                        .HasColumnType("int");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("LoanDocumentMasters");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanAccrual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AccruedDelayedInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AccruedInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DelayInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GSTOnProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("LoanNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OutstandingDelayedInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OutstandingInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OutstandingPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProcessingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalDelayedInterestPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalFeeWithGST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalInterestPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalPrincipalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalWaivedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LoanAccrual", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanDetail", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DelayInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DueDays")
                        .HasColumnType("int");

                    b.Property<decimal>("GSTPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProcessingFeeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanId");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanFee", b =>
                {
                    b.Property<int>("LoanFeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanFeeId"));

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFeeWithGST")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanFeeId");

                    b.HasIndex("LoanId")
                        .IsUnique();

                    b.ToTable("LoanFees");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanInstallment", b =>
                {
                    b.Property<int>("InstallmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstallmentId"));

                    b.Property<decimal>("AdjustedToDelayInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdjustedToFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdjustedToInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdjustedToPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DueDelayInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DueFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DueInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstallmentId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanInstallments");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanInterest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InterestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InterestId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanInterests");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.PendingInstallment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PendingInstallments");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.Waiver", b =>
                {
                    b.Property<int>("WaiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaiverId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstallmentId")
                        .HasColumnType("int");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaiverType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WaiverId");

                    b.HasIndex("LoanId");

                    b.ToTable("Waivers");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Location+City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Location+State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.AddressStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AddressStatuses", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.BankDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("is_credit_account")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BankDetails", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.BusinessCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BusinessCategories", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.BusinessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BusinessTypes", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.ChequeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChequeLocations", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EntityTypes", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Makes", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.PersonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PersonTypes", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.PurchaseSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsApplicationNoRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LoanBidAmtPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseSources", (string)null);
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.PurchaseSourceDocument1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchaseSourceId")
                        .HasColumnType("int");

                    b.Property<bool>("is_mandatory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseSourceId");

                    b.ToTable("PurchaseSourceDocuments1");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.RolePermission", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Authentication.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Authentication.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.User", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Authentication.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.DDR.DDR", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.BorrowerDetails", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", "Dealer")
                        .WithMany("BorrowerDetails")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.ChequeDetails", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", "Dealer")
                        .WithMany("ChequeDetails")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Authentication.User", "User")
                        .WithMany("Dealers")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.DocumentUpload", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.BorrowerDetails", "BorrowerDetails")
                        .WithMany()
                        .HasForeignKey("BorrowerDetailsId");

                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", "Dealer")
                        .WithMany("DocumentUploads")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.GuarantorDetails", "GuarantorDetails")
                        .WithMany()
                        .HasForeignKey("GuarantorDetailsId");

                    b.Navigation("BorrowerDetails");

                    b.Navigation("Dealer");

                    b.Navigation("GuarantorDetails");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.GuarantorDetails", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", "Dealer")
                        .WithMany("GuarantorDetails")
                        .HasForeignKey("DealerId");

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.SecurityDepositDetails", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", "Dealer")
                        .WithMany("SecurityDepositDetails")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.BuyerInfo", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", "Loan")
                        .WithOne("BuyerInfo")
                        .HasForeignKey("TscLoanManagement.TSCDB.Core.Domain.Loan.BuyerInfo", "LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.DDR.DDR", "DDR")
                        .WithMany()
                        .HasForeignKey("DDRId");

                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", "Dealer")
                        .WithMany("Loans")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanDetail", "LoanDetail")
                        .WithOne()
                        .HasForeignKey("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", "LoanDetailId");

                    b.Navigation("DDR");

                    b.Navigation("Dealer");

                    b.Navigation("LoanDetail");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.LoanAttachment", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", null)
                        .WithMany("Attachments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.LoanDocumentUpload", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", "Loan")
                        .WithMany("LoanDocumentUploads")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.LoanPayment", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", "Loan")
                        .WithMany("LoanPayments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.VehicleInfo", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.DDR.DDR", null)
                        .WithOne("VehicleInfo")
                        .HasForeignKey("TscLoanManagement.TSCDB.Core.Domain.Loan.VehicleInfo", "DDRId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", null)
                        .WithOne("VehicleInfo")
                        .HasForeignKey("TscLoanManagement.TSCDB.Core.Domain.Loan.VehicleInfo", "LoanId");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanDocuments.LoanDocumentActivity", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.LoanDocuments.LoanDocumentMaster", "LoanDocumentMaster")
                        .WithMany("Activities")
                        .HasForeignKey("LoanDocumentMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanDocumentMaster");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanDocuments.LoanDocumentMaster", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanFee", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanDetail", "Loan")
                        .WithOne("LoanFee")
                        .HasForeignKey("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanFee", "LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanInstallment", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanDetail", "Loan")
                        .WithMany("Installments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanInterest", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanDetail", "Loan")
                        .WithMany("Interests")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.Waiver", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanDetail", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Location+City", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Location+State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Masters.PurchaseSourceDocument1", b =>
                {
                    b.HasOne("TscLoanManagement.TSCDB.Core.Domain.Masters.PurchaseSource", "PurchaseSource")
                        .WithMany()
                        .HasForeignKey("PurchaseSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseSource");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Authentication.User", b =>
                {
                    b.Navigation("Dealers");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.DDR.DDR", b =>
                {
                    b.Navigation("VehicleInfo");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Dealer.Dealer", b =>
                {
                    b.Navigation("BorrowerDetails");

                    b.Navigation("ChequeDetails");

                    b.Navigation("DocumentUploads");

                    b.Navigation("GuarantorDetails");

                    b.Navigation("Loans");

                    b.Navigation("SecurityDepositDetails");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Loan.Loan", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("BuyerInfo");

                    b.Navigation("LoanDocumentUploads");

                    b.Navigation("LoanPayments");

                    b.Navigation("VehicleInfo");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanDocuments.LoanDocumentMaster", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.LoanInstallment.LoanDetail", b =>
                {
                    b.Navigation("Installments");

                    b.Navigation("Interests");

                    b.Navigation("LoanFee")
                        .IsRequired();
                });

            modelBuilder.Entity("TscLoanManagement.TSCDB.Core.Domain.Location+State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
